# Generated by Django 4.2.29 on 2026-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='tipo_detectado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
